# Dockerfile to create image with cron services
FROM alpine:latest
MAINTAINER mikael.marche@orange.com

RUN which crond && \
    rm -rf /etc/periodic

RUN apk update 

RUN set -x \
    && apk --no-cache add\
    python3 \
    py-pip \
    nano \
    && pip install virtualenv \
    && : # last line


# Install pip packages
COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN apk add --update tzdata
ENV TZ=Europe/Paris

COPY delcia_distrib /usr/src/delcia_distrib
# Set working directory for code
WORKDIR /usr/src/delcia_distrib

COPY entrypoint-alpine.sh ./entrypoint.sh
COPY delcia_tools_alpine.sh ./delcia_toos.sh
COPY delcia_tools_alpine.sh ./delcia_tools.sh
COPY delcia_conf_alpine.json ./delcia_conf.json
RUN chmod 755 ./delcia_toos.sh
RUN chmod 755 ./delcia_tools.sh

ENTRYPOINT ["./entrypoint.sh"]

#docker run --name delcia  -d  -p 2707:2707 mydelcia 
#see : https://www.airplane.dev/blog/docker-cron-jobs-how-to-run-cron-inside-containers
